# Generated by Django 4.0.6 on 2022-07-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_remove_product_quantity_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_femme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_femme', models.CharField(max_length=128)),
                ('slug_femme', models.SlugField(max_length=128)),
                ('price_femme', models.FloatField(default=0.0)),
                ('decription_femme', models.TextField(blank=True)),
                ('image_femme', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_homme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_homme', models.CharField(max_length=128)),
                ('slug_homme', models.SlugField(max_length=128)),
                ('price_homme', models.FloatField(default=0.0)),
                ('description_homme', models.TextField(blank=True)),
                ('image_homme', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
