# Generated by Django 4.0.6 on 2022-07-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_product_femme_product_homme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_montre',
        ),
    ]
