# Generated by Django 4.0.6 on 2022-07-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product_femme',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product_homme',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product_montre',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
