# Generated by Django 4.0.6 on 2022-07-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_remove_order_quantity_product_femme_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
