# Generated by Django 4.0.6 on 2022-08-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_remove_order_product_remove_order_user_delete_cart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_montre',
            new_name='Product_enfant',
        ),
    ]
