# Generated by Django 4.0.6 on 2022-08-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_article_commander_product_delete_product_enfant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_femmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=128)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Homme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product_homme', models.CharField(max_length=120)),
                ('slug_homme', models.SlugField(max_length=128)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
                ('description_homme', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_enfant',
        ),
        migrations.RenameField(
            model_name='product_enfant',
            old_name='description',
            new_name='description_enfant',
        ),
        migrations.RenameField(
            model_name='product_enfant',
            old_name='name_product',
            new_name='name_product_enfant',
        ),
        migrations.RenameField(
            model_name='product_enfant',
            old_name='slug',
            new_name='slug_enfant',
        ),
        migrations.AlterField(
            model_name='article',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.product_femmes'),
        ),
    ]
