# Generated by Django 4.0.6 on 2022-08-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='numero_telephone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
