# Generated by Django 4.0.6 on 2022-08-19 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online', '0009_article_commander_product_delete_product_enfant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comment', models.CharField(blank=True, max_length=125)),
                ('corps', models.TextField(max_length=200)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('Produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='online.product')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
