# Generated by Django 4.0.6 on 2022-08-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_product_femmes_product_homme_and_more'),
        ('commentaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='online.product_femmes'),
        ),
    ]
